source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'StatKit_Example', :exclusive => true do
  pod "StatKit", :path => "../"
end

target 'StatKit_Tests', :exclusive => true do
  pod "StatKit", :path => "../"

  
end
